### ISSUE TITLE
Bumblebee instantly closes

### ISSUE THREAD

**Issue by nijynot** [jaxcore/bumblebee-hotword-node#4]
Using your example in the README.md, the program instantly closes and outputs this:
```
ENVIRONMENT_IS_NODE /home/pi/bumblebee-wake-word/node_modules/bumblebee-hotword-node/lib/porcupine-v1.8/pv_porcupine.js
```
Any ideas on how to fix it? Or what's going wrong?

**Comment by dsteinman** [comment]
I removed the 'ENVIRONMENT_IS_NODE' console debug output in v0.0.9.  But that might not explain why it's crashing.

Which environment are you on, and which of the examples did you try?

**Comment by nijynot** [comment]
I tried this only
```js
const Bumblebee = require('bumblebee-hotword-node');
const bumblebee = new Bumblebee();
bumblebee.addHotword('bumblebee');

bumblebee.on('hotword', function (hotword) {
	console.log('Hotword Detected:', hotword);
});

bumblebee.start();
```

**Comment by dsteinman** [comment]
Are you on MacOS, Linux, or Windows?  And are you using v0.0.9?

Also, if you run node using `NODE_ENV=dev node start.js` you'll get more output.  In v0.0.9 I changed how the Porcupine files get loaded and this may be responsible.

**Comment by dsteinman** [comment]
Edit: I was mistaken, looks like the "ENVIRONMENT_IS_NODE" is still there in v0.0.9 (i fixed in the web version).

Are you using Windows, MacOSX, or Linux?  It's possible the location of `sox` is wrong.  I don't think I've actually  ever tried this in  Windows.  

I do have another larger voice project in the works, and it does work in Windows.  It runs Porcupine in a different way and runs DeepSpeech (speech-to-text) and speech synthesis as well https://github.com/jaxcore/bumblebee
